describe('Página inicial teste2', () => {
  beforeEach( () => {
    cy.visit('http://localhost:3000/')
  })
  beforeEach( () => {
    cy.visit('http://localhost:3000/')
  })
  it( 'Deve renderizar h1 com o texto correto!', () => {
    cy.checkTest('titulo-principal','Experimente mais liberdade no controle da sua vida financeira. Crie sua conta com a gente!' )
  })
  it( 'Deve renderizar h2 com o texto correto!', () => {
    cy.checkTest('vantagens','Vantagens do nosso banco:')
  })
  it( 'Deve renderizar h3 com o texto correto!', () => {
    cy.checkTest('titulo-vantagem01','Conta e cartão gratuitos')
    cy.checkTest('titulo-vantagem02','Saques sem custo')
    cy.checkTest('titulo-vantagem03','Programa de pontos')
    cy.checkTest('titulo-vantagem04','Seguro Dispositivos')
    cy.checkTest('servicos','Serviços')
    cy.checkTest('contato','Contato')
    cy.checkTest('autor','Desenvolvido por Alura')
  })
  it( 'Deve renderizar paragráfo com o texto correto!', () => {
    cy.checkTest('vantagem01','Isso mesmo, nossa conta é digital, sem custo fixo e mais que isso: sem tarifa de manutenção.')
    cy.checkTest('vantagem02','Você pode sacar gratuitamente 4x por mês de qualquer Banco 24h.')
    cy.checkTest('vantagem03','Você pode acumular pontos com suas compras no crédito sem pagar mensalidade!')
    cy.checkTest('vantagem04','Seus dispositivos móveis (computador e laptop) protegidos por uma mensalidade simbólica.')
    cy.checkTest('servicos1','Conta corrente')
    cy.checkTest('servicos2','Conta PJ')
    cy.checkTest('servicos3','Cartão de crédito')
    cy.checkTest('contato1','0800 004 250 08')
    cy.checkTest('contato2','meajuda@bytebank.com.br')
    cy.checkTest('contato3','ouvidoria@bytebank.com.br')
  })
  it( 'A imagem deve estar visível!', () => {
    cy.checkVisibility('imagemTitulo')
    cy.checkVisibility('imagemTitulo')
    cy.checkVisibility('imagem1')
    cy.checkVisibility('imagem2')
    cy.checkVisibility('imagem3')
    cy.checkVisibility('imagem4')
  })
  it( 'A div deve estar visível!', () => {
    cy.checkVisibility('div1')
    cy.checkVisibility('div2')
    cy.checkVisibility('div3')
    cy.checkVisibility('div4')
    cy.checkVisibility('div5')
    cy.checkVisibility('div6')
    cy.checkVisibility('div7')
    cy.checkVisibility('div8')
    cy.checkVisibility('div9')
  })
})
